# Generated by Django 5.1.5 on 2025-01-22 14:30

import django.db.models.deletion
import rest_framework_simplejwt.tokens
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('token_blacklist', '0012_alter_outstandingtoken_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeekpaAccessToken',
            fields=[
                ('blacklistedtoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='token_blacklist.blacklistedtoken')),
            ],
            bases=('token_blacklist.blacklistedtoken', rest_framework_simplejwt.tokens.AccessToken),
        ),
    ]
